### ISSUE TITLE
Add the plugin to Gradle Plugin repository

### ISSUE THREAD

**Issue by eximius313** [viswaramamoorthy/gradle-util-plugins#2]
If you add your plugin to the [Gradle Plugin Repository](https://plugins.gradle.org/) then applying the plugin would be even easier:
```
plugins {
  id "gradle-util-plugins" version "0.1.0-RELEASE"
}
```
and that's it - no need for additional `classpath` entries!

**Comment by eshepelyuk** [comment]
Nice proposal, ready to provide any help on this.

**Comment by viswaramamoorthy** [comment]
Thanks for the suggestion. I missed it. I have published to Gradle plugin portal now. Readme shows plugin id.
