### ISSUE TITLE
Support manifest based classpath for tasks extending JavaForkOptions

### ISSUE THREAD

**Issue by eshepelyuk** [viswaramamoorthy/gradle-util-plugins#4]
Currently manifest classpath is used only for `JavaExec` tasks. 

Since on windows `gradle test` also may fail because of long classpath, the plugin should support `Test` tasks and in fact all tasks extending `JavaForkOptions`

@viswaramamoorthy i'm ready to pick it up and provide a PR if you're currently busy.

**Comment by viswaramamoorthy** [comment]
If the underlying task for test is JavaExec based, this plug in will work
without any changes.

**Comment by eshepelyuk** [comment]
Apparently `org.gradle.api.tasks.testing.Test` is not `org.gradle.api.tasks.JavaExec` based, so changes inevitably required.

What I suggest is to change this plugin to apply manifest classpath for this interface `org.gradle.process.JavaForkOptions`, so all similar tasks including `Test` and `JavaExec` will be taken into account

**Comment by viswaramamoorthy** [comment]
Ok. Please go ahead and send PR

**Comment by eshepelyuk** [comment]
Ok, it  will take some time though, since I'm gonna introduce some testing support for plugin and then implement the change.

**Comment by eshepelyuk** [comment]
@viswaramamoorthy #5 is created, plz feedback

**Comment by eshepelyuk** [comment]
@viswaramamoorthy any updates / feedback ?

**Comment by eshepelyuk** [comment]
Since there's no feeback - I've release a clone version of this plugin.

https://github.com/eshepelyuk/gradle-util-plugins

**Comment by viswaramamoorthy** [comment]
That's fine. When I had my plugin version, I have not seen test tasks
failing and it solved problem that I have seen in compile tasks. I could
not reconcile how it was working for me while you reported that test task
failed.
